<a href="https://colab.research.google.com/github/sjkim25/Introduction-to-Artificial-Intelligence/blob/main/week2/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Diabetes Classification / Regression

In [ ]:
#경로
/content/drive/MyDrive/Colab Notebooks/diabetes.csv

In [76]:
import pandas as pd
import numpy as np

In [77]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

Classification

In [78]:
#결과값 Outcome을 제외한 데이터 X_clf에 저장
X_clf = df.drop('Outcome',axis=1)
X_clf.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [79]:
#결과값만 y_clf에 저장
y_clf = df['Outcome']
y_clf.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [80]:
from sklearn.model_selection import train_test_split

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_clf, y_clf, test_size=0.2, shuffle=True, random_state=12)
print(X_train_c.shape, y_train_c.shape)
print(X_test_c.shape, y_test_c.shape)

(614, 8) (614,)
(154, 8) (154,)

In [81]:
print ("==================================")
print (" ACCURACY OF OTHER ML CLASSIFIERS" )
print ("==================================")

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

==================================
 ACCURACY OF OTHER ML CLASSIFIERS
==================================

In [82]:
#Logistic Regression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train_c, y_train_c)

pred_lr = clf_lr.predict(X_test_c)

print ("\n--- LogisticRegression Classifier ---")
print (accuracy_score(y_test_c, pred_lr))
print (confusion_matrix(y_test_c, pred_lr))

--- LogisticRegression Classifier ---
0.8116883116883117
[[91  8]
 [21 34]]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [83]:
#Decision Tree
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train_c, y_train_c)

pred_dt = clf_dt.predict(X_test_c)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test_c, pred_dt))
print (confusion_matrix(y_test_c, pred_dt))

--- Decision Tree Classifier ---
0.7662337662337663
[[84 15]
 [21 34]]

In [84]:
#Random Forest
print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_c, y_train_c)
pred = rf_clf.predict(X_test_c)
print(accuracy_score(y_test_c,pred))
print (confusion_matrix(y_test_c, pred))

--- Radom Forest ---
0.7987012987012987
[[86 13]
 [18 37]]

Regression

In [85]:
df2=df.drop('Outcome',axis=1)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [86]:
#결과값 BMI를 제외한 데이터 X_reg에 저장
X_reg=df2.drop('BMI',axis=1)
X_reg.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,0.627,50
1,1,85,66,29,0,0.351,31
2,8,183,64,0,0,0.672,32
3,1,89,66,23,94,0.167,21
4,0,137,40,35,168,2.288,33

In [87]:
#결과값만 y_reg에 저장
y_reg=df2['BMI']
y_reg.value_counts()
y_reg

0      33.6
1      26.6
2      23.3
3      28.1
4      43.1
       ...
763    32.9
764    36.8
765    26.2
766    30.1
767    30.4
Name: BMI, Length: 768, dtype: float64

In [88]:
from sklearn.model_selection import train_test_split

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_reg, y_reg, test_size=0.2, shuffle=True, random_state=12)
print(X_train_r.shape, y_train_r.shape)
print(X_test_r.shape, y_test_r.shape)

(614, 7) (614,)
(154, 7) (154,)

In [89]:
#Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train_r, y_train_r)
ly_preds = model.predict(X_test_r)

print('평균제곱근오차', mean_squared_error(ly_preds, y_test_r))

def mse_np(actual, predicted):
    return np.mean((np.array(actual) - np.array(predicted)) ** 2)

print('평균제곱근오차', mse_np(ly_preds, y_test_r))

def mse(actual, predicted):
    sum_square_error = sum((a - p) ** 2 for a, p in zip(actual, predicted))
    mean_square_error = sum_square_error / len(actual)
    return mean_square_error

print('평균제곱근오차', mse(ly_preds, y_test_r))

평균제곱근오차 51.578866344300216
평균제곱근오차 51.578866344300216
평균제곱근오차 51.578866344300195

In [90]:
#Decision Tree
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(X_train_r, y_train_r)

from sklearn.metrics import mean_squared_error

dy_preds = model.predict(X_test_r)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test_r))

평균제곱근오차 82.96480519480518

In [91]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train_r, y_train_r)

from sklearn.metrics import mean_squared_error

ry_preds = model.predict(X_test_r)
print('평균제곱근오차', mean_squared_error(ry_preds, y_test_r))

평균제곱근오차 41.2279911038961