<a href="https://colab.research.google.com/github/sjkim25/Introduction-to-Artificial-Intelligence/blob/main/week3/Wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Wine Classification / Regression (LR, DT, RF, KNN)**

In [ ]:
#경로
/content/drive/MyDrive/Colab Notebooks/wine.csv

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/wine.csv")
df

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

**// Classification //**

In [5]:
#결과값 label을 제외한 데이터 X에 저장
X_clf = df.drop('Wine',axis=1)
X_clf.head()

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [6]:
#결과값만 y에 저장
y_clf = df['Wine']
y_clf.head()

0    1
1    1
2    1
3    1
4    1
Name: Wine, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_clf, y_clf, test_size=0.2, shuffle=True, random_state=12)
print(X_train_c.shape, y_train_c.shape)
print(X_test_c.shape, y_test_c.shape)

(142, 13) (142,)
(36, 13) (36,)

In [8]:
print ("==================================")
print (" ACCURACY OF OTHER ML CLASSIFIERS" )
print ("==================================")

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

==================================
 ACCURACY OF OTHER ML CLASSIFIERS
==================================

In [9]:
#Logistic Regression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train_c, y_train_c)

pred_lr = clf_lr.predict(X_test_c)

print ("\n--- LogisticRegression Classifier ---")
print (accuracy_score(y_test_c, pred_lr))
print (confusion_matrix(y_test_c, pred_lr))

--- LogisticRegression Classifier ---
0.9722222222222222
[[14  0  0]
 [ 0 10  1]
 [ 0  0 11]]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [10]:
#Decision Tree
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train_c, y_train_c)

pred_dt = clf_dt.predict(X_test_c)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test_c, pred_dt))
print (confusion_matrix(y_test_c, pred_dt))

--- Decision Tree Classifier ---
0.9166666666666666
[[14  0  0]
 [ 1 10  0]
 [ 2  0  9]]

In [11]:
#Random Forest
print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_c, y_train_c)
pred = rf_clf.predict(X_test_c)
print(accuracy_score(y_test_c,pred))
print (confusion_matrix(y_test_c, pred))

--- Radom Forest ---
1.0
[[14  0  0]
 [ 0 11  0]
 [ 0  0 11]]

In [12]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train_c, y_train_c)

KNeighborsClassifier(n_neighbors=6)

In [13]:
from sklearn import metrics

y_pred = knn.predict(X_test_c)
print(accuracy_score(y_test_c, y_pred))

0.75

**// Regression //**
 - Alcohol

In [14]:
df2=df.drop('Wine',axis=1)
df.head()

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [15]:
#Alcohol을 결과값으로 지정, 결과값을 제외한 데이터를 X에 저장
X_reg = df2.drop('Alcohol',axis=1)
X_reg.head()

,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [16]:
#결과값을 y에 저장
y_reg = df2['Alcohol']
y_reg.value_counts()
y_reg

0      14.23
1      13.20
2      13.16
3      14.37
4      13.24
       ...
173    13.71
174    13.40
175    13.27
176    13.17
177    14.13
Name: Alcohol, Length: 178, dtype: float64

In [17]:
from sklearn.model_selection import train_test_split

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_reg, y_reg, test_size=0.2, shuffle=True, random_state=12)
print(X_train_r.shape, y_train_r.shape)
print(X_test_r.shape, y_test_r.shape)

(142, 12) (142,)
(36, 12) (36,)

In [18]:
#Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train_r, y_train_r)
ly_preds = model.predict(X_test_r)

print('평균제곱근오차', mean_squared_error(ly_preds, y_test_r))

def mse_np(actual, predicted):
    return np.mean((np.array(actual) - np.array(predicted)) ** 2)

print('평균제곱근오차', mse_np(ly_preds, y_test_r))

def mse(actual, predicted):
    sum_square_error = sum((a - p) ** 2 for a, p in zip(actual, predicted))
    mean_square_error = sum_square_error / len(actual)
    return mean_square_error

print('평균제곱근오차', mse(ly_preds, y_test_r))

평균제곱근오차 0.2933576216695043
평균제곱근오차 0.2933576216695043
평균제곱근오차 0.29335762166950435

In [19]:
#Decision Tree
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(X_train_r, y_train_r)

from sklearn.metrics import mean_squared_error

dy_preds = model.predict(X_test_r)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test_r))

평균제곱근오차 0.5067027777777783

In [20]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train_r, y_train_r)

from sklearn.metrics import mean_squared_error

ry_preds = model.predict(X_test_r)
print('평균제곱근오차', mean_squared_error(ry_preds, y_test_r))

평균제곱근오차 0.27696869999999985

In [21]:
#KNN
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=6)
knn.fit(X_train_r, y_train_r)

KNeighborsRegressor(n_neighbors=6)

In [22]:
y_pred = knn.predict(X_test_r)

from sklearn import metrics
y_pred = knn.predict(X_test_r)
print(mean_squared_error(y_test_r, y_pred))

0.4101260802469143